### ISSUE TITLE
Unable to launch new build - fails while generating chunks.

### ISSUE THREAD

**Issue by T012m3n7oR** [FTBTeam/FTB-Unstable-1.14#23]
Launch Log: https://paste.feed-the-beast.com/view/409279bc

Appears to be trying to do something with a deep ocean biome during map creation.
Prevents the server from loading.
I am running forge 28.0.55, launching the server from a Ubuntu Server 18.04, although that shouldn't matter.  Have a capped memory limit of 16GB.

Details:
	Id: minecraft:decorated
	Description: < DecoratedFeature [minecraft:decorated] >
Stacktrace:
	at net.minecraft.world.biome.Biome.func_203608_a(Biome.java:283)

-- Generation --
Details:
	CenterX: 2
	CenterZ: -13
	Step: SURFACE_STRUCTURES
	Seed: -7373836249778895336
	Biome: minecraft:deep_ocean
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_202092_b(SourceFile:130)
	at net.minecraft.world.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:73)
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:196)

-- Chunk to be generated --
Details:
	Location: 2,-13
	Position hash: -55834574846
	Generator: net.minecraft.world.gen.OverworldChunkGenerator@36896cd2
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$17(ChunkManager.java:509)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.world.server.ChunkManager.lambda$func_223156_b$19(ChunkManager.java:507)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:83)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:123)
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:91)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by T012m3n7oR** [comment]
I believe this was my fault.  Didn't copy configs/other files other than jar files.  My bad!
